name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted  # Use the self-hosted runner instead of GitHub's default server

    steps:
    - uses: actions/checkout@v4
    - name: Pull latest changes in cloned folder
      run: |
        cd /var/www/python-cicd
        git reset --hard origin/main  # Discard local changes
        git pull origin main
        echo "Repository updated successfully!"
